hive_version: 1.2.2
hive_url: "http://www-us.apache.org/dist/hive/hive-{{hive_version}}/apache-hive-{{hive_version}}-bin.tar.gz"
repo_dir: /opt
install_dir: /opt
# hadoop_dir: "{{ install_dir }}/hadoop-{{hadoop_version}}"