- name: Create a the file /etc/profile.d/hive.sh  if it does not exist
  file:
    path: /etc/profile.d/hive.sh
    state: touch

- name: Adding the path in the Profile files
  lineinfile:
    path: /etc/profile.d/hive.sh
    ###
    ### Regex: For state=present, the pattern to replace if found. Only the last line found will be replaced.
    ### If the regular expression is not matched,
    ### the line will be added to the file in keeping with insertbefore or insertafter settings.
    ### => find all the occurences matching this regex,
    ### if found replace the last occurence with the 'line' content,
    ### if no occurences are found insert the line as specified with insertbefore or insertafter params.
    regexp: 'export HIVE_HOME='
    state: present
    line: 'export HIVE_HOME=/opt/apache-hive-1.2.2-bin'
    insertafter: 'EOF'

- name: Adding the path in the Profile files
  lineinfile:
    path: /etc/profile.d/hive.sh
    ###
    ### Regex: For state=present, the pattern to replace if found. Only the last line found will be replaced.
    ### If the regular expression is not matched,
    ### the line will be added to the file in keeping with insertbefore or insertafter settings.
    ### =>with state=present find all the occurences matching this regex,
    ### if found replace the last occurence with the 'line' content,
    ### if no occurences are found insert the line as specified with insertbefore or insertafter params.
    regexp: 'PATH='
    state: present
    line: 'PATH=$PATH:$HIVE_HOME/bin'
    insertafter: 'EOF'