- name:
  hosts: all
  connection: local
    # Setting gather_facts: False on a playbook allows this implicit fact gathering to be skipped.
  gather_facts: False
  become: yes
  roles:
    - java
    - hadoop
    - hive_server_mode
    - spark
    # - impala
